language: rust
sudo: false
cache: cargo
matrix:
  include:
  - rust: beta
    env: RUST_BACKTRACE=1
    before_script:
    - cargo install wasm-pack
    - cargo install cargo-generate
    script:
    - cargo generate --git . --name testing
    - mv Cargo.toml Cargo.toml.tmpl
    - cd testing
    - wasm-pack build
    - wasm-pack test --node
  - rust: nightly
    env: RUST_BACKTRACE=1
    before_script:
    - rustup target add wasm32-unknown-unknown
    - cargo install cargo-generate
    script:
    - cargo generate --git . --name testing
    - mv Cargo.toml Cargo.toml.tmpl
    - cd testing
    - cargo check
    - cargo check --target wasm32-unknown-unknown
  - rust: beta
    env: RUST_BACKTRACE=1
    before_script:
    - rustup target add wasm32-unknown-unknown
    - cargo install cargo-generate
    script:
    - cargo generate --git . --name testing
    - mv Cargo.toml Cargo.toml.tmpl
    - cd testing
    - cargo check
    - cargo check --target wasm32-unknown-unknown